import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react';
import styles from '../styles/Home.module.css'

import './common.css';
import './index-style.css';
import { NewsSection } from './NewsSection';

function MyInput() {
  const [inputVal, updateVal] = React.useState("");
  const onchange = React.useCallback((e: any) => {
    console.log(e.target.value);
    updateVal(e.target.value);
  }, []);
  return (
    <div style={{ textAlign: 'center' }}>
      <input type="text" onChange={onchange}></input>
      <p>{inputVal}</p>
    </div>
  )
}

function LinkedText(props: any): JSX.Element {
  return (
    <div style={{ textAlign: 'center' }}>
      <a href={props.link} target="_blank" className="news-title">{props.text}</a>
    </div>
  );
}

interface NewsTextProps {
  titleText?: string;
  children?: React.ReactNode;
  center?: boolean;
};

function NewsTitle(props: NewsTextProps): JSX.Element {
  return <div className={"news-title " + (props.center ? "center" : "")}>{props.titleText || props.children || "No Text"}</div>;
}

function AkebiNews(): JSX.Element {
  const LinkOfAkebiOfficialSite = "https://akebi-chan.jp/";
  return (<div className="akebi-news">
    <NewsTitle titleText="布教" center />:
    <MyInput />
    <NewsTitle titleText="明日ちゃんのセーラー服 NEWS" center />
    <LinkedText link={LinkOfAkebiOfficialSite} text="公式サイト"></LinkedText>
    <NewsSection />
  </div>);
}

function Wrapper(): JSX.Element {
  return (<div className="wrapper">
    <AkebiNews />
  </div>);
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Akebi News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charSet="utf-8" />
        {/* <link rel="icon" href="%PUBLIC_URL%/favicon.ico" /> */}
        {/* 表示領域を指定するメタタグ --> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* ブラウザの検索タグの色を設定するメタタグ */}
        <meta name="theme-color" content="white" />
        <meta name="description" content="Web site created using create-react-app" />
        <script async src="https://platform.twitter.com/widgets.js" charSet="utf-8" />
      </Head>

      <main className={styles.main}>
        <Wrapper />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
